version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME:-wallet}
      - POSTGRES_USER=${DB_USERNAME:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-root}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  wallet-app:
    build: .
    image: wallet-app:latest
    container_name: wallet-app
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
        - DB_HOST=postgres
        - DB_PORT=5432
        - DB_NAME=wallet
        - DB_USERNAME=postgres
        - DB_PASSWORD=root
        - JPA_DDL_AUTO=none
        - SHOW_SQL=true
        - APP_PORT=8080
        - LOGGING_LEVEL_APP=DEBUG
        - LOGGING_LEVEL_SPRING=INFO
        - logging_level_hibernate_SQL=DEBUG
        - HIKARI_MAX_POOL_SIZE=20
        - HIKARI_MIN_IDLE=5
        - HIKARI_CONNECTION_TIMEOUT=30000
        - TOMCAT_MAX_THREADS=400
        - SPRING_LIQUIBASE_ENABLED=true
        - SPRING_LIQUIBASE_CHANGE_LOG=classpath:db/changelog/db.changelog-master.xml
    depends_on:
      postgres:
        condition: service_healthy
    networks:
        - app-network

volumes:
    postgres-data:
networks:
    app-network:
      driver: bridge