version: '3.8'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: wallet
    volumes:
        - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  wallet-app:
    build: .
    image: wallet-app:latest
    container_name: wallet-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/wallet
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
      SPRING_LIQUIBASE_ENABLED: true
      LIQUIBASE_ENABLED: true
      LIQUIBASE_CHANGELOG: classpath:db/changelog/db.changelog-master.xml
    depends_on:
      - postgres

volumes:
    postgres_data: